services:
  redis:
    image: redis:7.0-alpine
    container_name: water-aur-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data

  mongodb:
    image: mongo:7.0
    container_name: water-aur-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_USERNAME: water-aur-redis
    volumes:
      - mongo-data:/data/db

volumes:
  redis-data:
  mongo-data:
